### ISSUE TITLE
Cannot use `prepend` option with empty string

### ISSUE THREAD

**Issue by feimosi** [dvinciinteractive/gulp-inject-version#3]
If I use the `prepend` option with an empty string `''`, it gets ignored. That's because in JavaScript empty strings are evaluated to false. You'd have to change the code to check against undefined value or use `''` as default.

**Comment by JAAulde** [comment]
Hello! Thanks for checking out the plugin, and for reporting your issue.

Help me make sure I understand you correctly, please--I default the `prepend` to the value of 'v', and you don't want anything (including 'v') prepended, so you pass an empty string. This is being ignored die to the logic I used, so you get the 'v' anyway. Is this correct?

Thanks,
Jim

**Comment by feimosi** [comment]
Hi, that's right, exactly as you've described it.
Regards,
Marek

**Comment by JAAulde** [comment]
I've fixed, tested, released, and published. Check it out and let me know how it does for you.

Thanks!

**Comment by feimosi** [comment]
I can confirm, everything works fine. Thanks a lot!

**Comment by JAAulde** [comment]
Thanks very much for confirming, and for closing the issue.

Happy coding!

**Comment by staff0rd** [comment]
Strangely I have found this bug does not exist on my Windows build.  However when building OSX the bug is evident.

Regardless, I have confirmed the fix on OSX also - can you please upload this fix to npm?
