### ISSUE TITLE
Error: package.json not valid JSON

### ISSUE THREAD

**Issue by Ross-Rawlins** [dvinciinteractive/gulp-inject-version#6]
I am trying to run gulp inject version after I run gulp bump but I keep getting the error invalid json, but if I run this individually they run fine. Please can you help me fix this.

**Comment by JAAulde** [comment]
HI, Kratos-SA,

I no longer have direct access to edit the code as I've left the organization. As this issue may not require a code change I can, however, make an attempt to help you via advice or guidance.

Can you please provide me a link to the gulp bump package you're using and an example of a gulp file that would cause this issue?

Thanks,
Jim

**Comment by Kratos-SA** [comment]
Hi Jim

Thanks for getting back; no stress I was able to resolve my issue.

On 21 May 2016 at 17:24, Jim <notifications@github.com> wrote:

> HI, Kratos-SA,
>
> I no longer have direct access to edit the code as I've left the
> organization. As this issue may not require a code change I can, however,
> make an attempt to help you via advice or guidance.
>
> Can you please provide me a link to the gulp bump package you're using and
> an example of a gulp file that would cause this issue?
>
> Thanks,
> Jim
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dvinciinteractive/gulp-inject-version/issues/6#issuecomment-220783644>
>



-- 
Ross Rawlins
*Tel:* 021 531 7087
*Cell:* 072 424 9480
*Skype:* ross.rawlins
*Email:* ross@duovili.co.za

<http://www.duovili.co.za>
<https://plus.google.com/113781084234234096576/posts>
<https://www.facebook.com/Duovili>
<http://www.linkedin.com/company/duovili/>     <https://twitter.com/Duovili>


This e-mail message and all attachments contain the CONFIDENTIAL AND
PROPRIETARY information of DUOVILI DEVELOPMENTS. and may contain LEGALLY
PRIVILEGED information. If you are not the intended recipient, you are
hereby notified that any disclosure, distribution, or use of this e-mail,
its attachments or any information contained therein is unauthorised and
prohibited. If you have received this in error, please contact the sender
immediately and delete this e-mail and any attachments.

**Comment by JAAulde** [comment]
Thanks for getting back to me, Kratos-SA. Will recommend closure of this issue.

**Repo owner:** recommend closure with no action.

**Comment by JAAulde** [comment]
_bump_

**Comment by ClickerMonkey** [comment]
I don't have access, who does have control over the repo Jim?

**Comment by JAAulde** [comment]
Hmm, I assumed anyone who was in the organization. Many of the members are not publicly listed, so I can't see who all is in the org to make a guess. I suppose Alan was an admin, and I don't know what he idd with his membership upon his departure.
