### ISSUE TITLE
Only first occurrence is replaced

### ISSUE THREAD

**Issue by dboyd-atl** [dvinciinteractive/gulp-inject-version#7]
if I have:

```
var a = "%%GULP_INJECT_VERSION%%";
var b = "%%GULP_INJECT_VERSION%%";

```

after building I get:

```
var a = "v1.0.0";
var b = "%%GULP_INJECT_VERSION%%";
```

This is due to the replace() function used only replacing the first occurrence.

I workaround at the moment by doing this in my Gulpfile:

```
.pipe(injectVersion({
              replace: /%%GULP_INJECT_VERSION%%/g
        }))

```

which is a bit ugly. Would it be possible to add an option to 'replaceall' pls?

(Also, great package!, thanks for contributing this)

**Comment by JAAulde** [comment]
HI dboyd-atl,

I had never even considered the idea of the search subject showing up more than once in a file. Now that you bring it up, it's kind of an obvious need!

I really like the way you fixed it via an adjusted `replace` option--very smart. I agree, however, that the plugin should consider the need multiple replacement.

I no longer have direct access to work on the code as I've left the organization. I'll take a look and if I come up with a solution I like, I'll fork this and make then change, then submit a pull request.

Thanks for the report!
Jim

**Comment by JAAulde** [comment]
_bump_

**Comment by rywalsh** [comment]
Agree with @JAAulde - the workaround proposed by @dboyd-atl worked for me too - IMO this should either become part of the documentation or part of the repo. 👍 #8

**Comment by ClickerMonkey** [comment]
Merged and new version created.

Sorry for the long delay everyone, I didn't have proper permissions for the longest time.
